### PR TITLE
Blacklist guiYMOUR as a mod author

### PR DESCRIPTION
**Pull request by AzhurniyBaklan**
guiYMOUR has 2 main mods on the account. Both are disgusting to the mod community as a whole and might be considered disrespectful.
I. https://github.com/guiYMOUR/mindustry-creator-mod

- Sprite lag
  Some sprites are not put into proper folders. The amount of content this mod has causes obnoxious sprite lag. Some folders have folders inside folders.
  Examples:
  
image
image

- Stolen assets and just straight up content spam
 Some sprites are taken from vanilla
  Example:
 
image

Some sprites are just recolors of each other
 Examples:
image
image
image
image

Some sprites are probably taken from google images or straight up other games, such as Starcraft II on ex.2
 Examples:
image
image
image

Copyrighted images are taken without permission
Example:
image

Stolen sprites from other mods
Examples:
image
image

- Copyrighted scripts use without permission
Examples:
https://github.com/guiYMOUR/mindustry-creator-mod/blob/main/scripts/UI/areas.js
https://github.com/guiYMOUR/mindustry-creator-mod/blob/main/scripts/UI/library.js
https://github.com/guiYMOUR/mindustry-creator-mod/blob/main/scripts/paota/DC.js

-Straight up lying in the description
 
image
image

And 2.https://github.com/guiYMOUR/mindustry-Extra-Utilities-mod isn't that bad, but it still has issues listed above, such as:
image
stolen from AC
image

With all that in mind, I ask you to blacklist this author for good.

### CODE REVIEW

**Comment by guiYMOUR** [comment]
I have changed the texture, and this ripple is not from AC, but my texture artist painted it himself.
creator modI was only part of it, not mine, but my friend's.
And you, I think more should be banned, you do not know the facts of the case that I plagiarized, said I this is not that is not right.

**Comment by guiYMOUR** [comment]
AC is the 5.0 version mod, and I made it all by my own hand.

**Comment by guiYMOUR** [comment]
Now that you have succeeded in banding me, you are very happy right?

**Comment by guiYMOUR** [comment]
@Anuken

**Comment by guiYMOUR** [comment]
you can banned creator Because it's not mine, and my friend only wants to put it on github and not into the mod browser.but please, Don't blacklist my mod, thank you.I may have updates in the future.

**Comment by no9527dada** [comment]
我来了，我是创世神MOD的作者9527 来此吃瓜看戏 加油

**Comment by no9527dada** [comment]
创世神MOD是我做的，和guiYMOUR没有任何关系哦。他只是待我发表而已，真是苦了guiY了

**Pull request closed without merging**
