### PR TITLE
Blacklist braindustry

### PR DESCRIPTION
**Pull request by QmelZ**
This mod breaks just about everything, including some vanilla stuff. I think it should be removed from the browser.

### CODE REVIEW

**Comment by BlueWolf3682** [comment]
I'm behind QmelZ on this. Braindustry breaks every JavaScript mod and from what I have seen, the vanilla Bloom setting.

**Comment by sk7725** [comment]
I too support this, for the reasons said above.

**Comment by MEEPofFaith** [comment]
~~And this is why you don't port to Java unless you know what you're doing.~~

**Comment by GlennFolker** [comment]
I support this. Hard work and environment-friendly do not correlate, so let us not take the effort and pain into making this mod as then again, it breaks compatibility with other mods by _a lot_.

This is an [example](https://github.com/pixaxeofpixie/Braindustry-Mod/blob/892403f3afb0acf21b4ec10a2a287059c35d2b09/core/src/braindustry/BraindustryMod.java#L163) of the totally destructive action of theirs. They are literally replacing every instance of `LightningBulletType` into their own implementation of it, _without_ taking custom fields, functions, type inheritance, and unsafe casting from the using mod into account, and that is purely disgusting and unbearable.

**Comment by sk7725** [comment]
upon further research: braindustry replaces half the main classes (ex. Player(Comp).java, Net.java) with their own classes, nullifying any compatibility with js(prohibited), java mods or plugins/custom clients(classCast).

**Comment by sk7725** [comment]
Screenshot_20210512-002028

**Comment by MEEPofFaith** [comment]
~~oh hey, Testing Utilities fits perfectly~~

**Comment by lordReddx** [comment]
It's begin

**Comment by summetdev** [comment]
+1 for this

**Comment by GlennFolker** [comment]
~~when merge~~

**Comment by AzhurniyBaklan** [comment]
> ~when merge~

never, qmelz forgot to unconflict files

**Comment by QmelZ** [comment]
> qmelz forgot to unconflict files
yes

**Review by kotasusmogus — APPROVED** [review]

**Comment by MEEPofFaith** [comment]
EMERGENCY SITUATION
It appears that pixie has gone insane and/or been hacked as Braindustry suddenly appears to be malicious as of 9 hours ago.

**Comment by Anuken** [comment]
yes

**Comment by SunkyMP3G** [comment]
The best PR in my life - saved my PC. Very late thanks

**Pull request closed without merging**
