### PR TITLE
Hide spam mods

### PR DESCRIPTION
**Pull request by buthed010203**
These are all just forks of examplemod (except for that last one which requires a bleeding edge version)

### CODE REVIEW

**Comment by sk7725** [comment]
why is ozone removed?

**Comment by sk7725** [comment]
Also, it might be that the modder may be working on changes that aren't pushed yet. Every mod does start from a fork.

**Comment by buthed010203** [comment]
> Also, it might be that the modder may be working on changes that aren't pushed yet. Every mod does start from a fork.

That is true however none of them have been updated in the last 6 months so I highly doubt that they will push anything any time soon

**Comment by buthed010203** [comment]
> why is ozone removed?

o7 is already in the blacklist, no point blacklisting it twice

**Comment by sk7725** [comment]
> > why is ozone removed?
> 
> o7 is already in the blacklist, no point blacklisting it twice

its.....2 different owners? "o7" != "o7-fire"

**Comment by buthed010203** [comment]
> > > why is ozone removed?
> > 
> > 
> > o7 is already in the blacklist, no point blacklisting it twice
> 
> its.....2 different owners? "o7" != "o7-fire"

Its a regex...

**Comment by Anuken** [comment]
Added a check for example mod names instead.

**Pull request closed without merging**
